### ISSUE TITLE
Alternative deployment methods and persistance backends

### ISSUE THREAD

**Issue by bjornharrtell** [ITfoxtec/FoxIDs#471]
It would be nice if it was possible to optionally supply an existing app service plan to use. Rationale is when you have many small environments that already share app service plan(s) and you want to avoid introducing a new app service plan for each of these environments when integrating FoxID into them.

## TODO

* [ ] Alternative deployment menthods (via devops or github pipeline? target k8s infrastructure?=
* [ ] Pluggable database backend + PostgreSQL as alt
* [ ] https://github.com/ITfoxtec/FoxIDs/issues/742

**Comment by bjornharrtell** [comment]
I agree slots seems like a good idea when you require minimal downtime.

But "cloud solution" can mean many things. For example it could be desirable to run FoxID as a fully containerized solution on kubernetes cluster which solves concurrent/switchable deployments natively in another way.

**Comment by Revsgaard** [comment]
You are probably right about Kubernetes cluster, not something I have much knowledge about.

**Comment by bjornharrtell** [comment]
No longer interesting to reuse app service plans. But it could be interesting to be able to run containerized in fx. Kubernetes. However that means need to find alternatives to CosmosDB and Azure Keyvault.

**Comment by bjornharrtell** [comment]
It's possible to integrate cloud provided secrets using https://secrets-store-csi-driver.sigs.k8s.io/concepts.html#provider-for-the-secrets-store-csi-driver. For test/development purposes could rely on native built in (insecure) k8s secrets.

**Comment by bjornharrtell** [comment]
A more or less direct replacement for CosmosDB is MongoDB. Could also use PostgreSQL (jsonb column).

**Comment by bjornharrtell** [comment]
A more or less direct replacement for CosmosDB is MongoDB. Could also use PostgreSQL (jsonb column).
